### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not absolute

### ISSUE THREAD

**Issue by EmergReanimator** [kwin/cppcheclipse#101]
Hi there,

I experience java exception on a given project under Windows 7 only with 	cppcheclipse 1.1.0.v20160724-1648.

**Configuration**
eclipse.buildId=4.12.0.I20190605-1800
java.fullversion=1.8.0_232-b09
JRE 1.8.0 Windows 7 amd64-64-Bit Compressed References 20191106_498 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc1
JCL      - 3504dff40aa based on jdk8u232-b09
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.cpp.product

**cppcheck is installed at default location.**
![image](https://user-images.githubusercontent.com/13292029/70248072-b185b400-177a-11ea-81a1-85ea059face1.png)

**Here is error log:**
> java.lang.IllegalArgumentException: URI is not absolute
	at java.io.File.<init>(File.java:416)
	at com.googlecode.cppcheclipse.ui.ToolchainSettings.resolveIncludePath(ToolchainSettings.java:139)
	at com.googlecode.cppcheclipse.ui.ToolchainSettings.getIncludes(ToolchainSettings.java:195)
	at com.googlecode.cppcheclipse.ui.ToolchainSettings.getUserIncludes(ToolchainSettings.java:87)
	at com.googlecode.cppcheclipse.core.Checker.<init>(Checker.java:80)
	at com.googlecode.cppcheclipse.ui.Builder$ResourceVisitor.initChecker(Builder.java:164)
	at com.googlecode.cppcheclipse.ui.Builder$ResourceVisitor.processFile(Builder.java:199)
	at com.googlecode.cppcheclipse.ui.Builder$ResourceVisitor.visit(Builder.java:122)
	at org.eclipse.core.internal.resources.Resource.lambda$1(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource$$Lambda$636.0000000000000000.visit(Unknown Source)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.resources.Resource$$Lambda$332.0000000000000000.visitElement(Unknown Source)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at com.googlecode.cppcheclipse.ui.Builder.processResource(Builder.java:306)
	at com.googlecode.cppcheclipse.ui.commands.RunCodeAnalysis$RunCodeAnalysisJob.runResource(RunCodeAnalysis.java:26)
	at com.googlecode.cppcheclipse.ui.commands.ResourceSelectionJob.run(ResourceSelectionJob.java:44)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by kwin** [comment]
Probably already fixed by https://github.com/kwin/cppcheclipse/pull/85. Please try to build from sources and see if the issue vanishes.

**Comment by EmergReanimator** [comment]
I finally managed to address this issue. Now I can confirm that 1.1.1 fixes #101;

**Would it be possible for you to publish v1.1.1 on p2 repository?**

[com.googlecode.cppcheclipse.repository-1.1.1.v20200225-1507.zip](https://github.com/kwin/cppcheclipse/files/4250730/com.googlecode.cppcheclipse.repository-1.1.1.v20200225-1507.zip)

![image](https://user-images.githubusercontent.com/13292029/75261604-99f32000-57eb-11ea-9d90-07303f8f4316.png)

On Market place one can find only 1.1.0 from Jul 24, 2016
![image](https://user-images.githubusercontent.com/13292029/75261665-b000e080-57eb-11ea-929f-555bb69ef6da.png)

**Comment by kwin** [comment]
As you can see in https://github.com/kwin/cppcheclipse/releases 1.1.1 is not yet released.

**Comment by EmergReanimator** [comment]
I see. 
Is any particular reason that preventing release of v1.1.1?
Is anything that I may do to make this happen?

**Comment by EmergReanimator** [comment]
I may confirm that https://github.com/kwin/cppcheclipse/releases/tag/1.1.1 fixes #101
@kwin @AntonKrug: Thanks for support and the release so far!
